name: teachme-auth-service

services:
  auth-service:
    build:
      context: ./services/teachme-auth-service
      dockerfile: Dockerfile
      secrets:
        - source: maven_settings
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SECRET_KEY
      - MONGODB_URI=mongodb://user:pass@auth-service-mongo-db:27017
      - SPRING_DATA_MONGODB_DATABASE=user
      - SENDGRID_API_KEY 
    ports:
      - "8080"
      - "35729"
    depends_on:
      - mongo-db
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-auth-service.rule=Host(`teachme-auth-service.localhost`)"
      - "traefik.http.services.teachme-auth-service.loadbalancer.server.port=8080"

  mongo-db:
    image: mongodb/mongodb-community-server:6.0.12-ubi8
    container_name: auth-service-mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27020:27017"
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-auth-service-db.rule=Host(`teachme-auth-service.db.localhost`)"
      - "traefik.http.services.teachme-auth-service-db.loadbalancer.server.port=8080"

secrets:
  maven_settings:
    file: ~/.m2/settings.xml

networks:
  teachme-network:
    external: true
  proxy-network:
    external: true
