name: certification-service

services:
  certification-service:
    build:
      context: ./services/teachme-certification-service/
      dockerfile: Dockerfile
    container_name: certification_service
    environment:
      - MONGO_DATABASE=certificate_db
      - MONGO_COLLECTION_NAME=student_certificates
      - MONGODB_URI_USER=mongodb://user:pass@certification_mongodb:27017/certificate_db?authSource=admin
      - AZURE_STORAGE_ACCOUNT_NAME=devstoreaccount1
      - AZURE_STORAGE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - BLOB_STORAGE_CONTAINER_NAME=certificates
      - BLOB_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - CERTIFICATES_DIR=/app/certificates
      - PFX_PASSPHRASE=mysecurepassphrase
      - SIGNATURE_FIELD_NAME=Signature1
      - SIGNATURE_BOX=150,30,450,90
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - QR_CODE_URL=https://www.youtube.com/watch?v=dQw4w9WgXcQ
      - FLASK_ENV=development
    ports:
      - "8080"
      - "35729"
    volumes:
      - ./services/teachme-certification-service/certificates:/certification-service/certificates
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-certification-service.rule=Host(`teachme-certification-service.localhost`)"
      - "traefik.http.services.teachme-certification-service.loadbalancer.server.port=8080"

  mongodb:
    image: mongo:latest
    container_name: certification_mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=user
    - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27026:27017"
    volumes:
      - ./services/teachme-certification-service/mongodb/mongod.conf:/etc/mongo/mongod.conf
    healthcheck:
      test: mongosh --quiet --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-certification-service-db.rule=Host(`teachme-certification-service.db.localhost`)"
      - "traefik.http.services.teachme-certification-service-db.loadbalancer.server.port=8080"

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    expose:
      - 10000
      - 10001
      - 10002
    ports:
      - "11000:10000"  # Since 1000 is already in use
      - "11001:10001"  
      - "11002:10002"  
    networks:
      - teachme-network


volumes:
  mongodb_data:
    driver: local

networks:
  teachme-network:
    external: true
  proxy-network:
    external: true