services:
  teachme-frontend:
    build:
      context: ./services/teachme-frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - teachme-network

networks:
  teachme-network:
    external: true
