services:
  rating-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      FEATURE_FLAG: "true"
      API_ENDPOINT: "http://api/v1/course/{courseId}/ratings"
      MONGODB_URI: "mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.bpad4.mongodb.net/"

    env_file:
      - .env
