name: teachme-student-service

services:
  student-service:
    build:
      context: ./services/teachme-student-service
      dockerfile: Dockerfile.dev
      secrets:
        - source: maven_settings
    container_name: student-service
    env_file:
      - .env.dev
    volumes:
      - ./services/teachme-student-service:/app
      - ./services/teachme-student-service/target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - BLOB_STORAGE_CONTAINER_NAME=profile-pictures
      - BLOB_STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://blob-storage:10000
      - SECURITY_JWT_SECRET_KEY
    ports:
      - "8080"
      - "35729"
    depends_on:
      - mongo-db
      - redis-cache
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-student-service.rule=Host(`teachme-student-service.localhost`)"
      - "traefik.http.services.teachme-student-service.loadbalancer.server.port=8080"

  mongo-db:
    image: mongodb/mongodb-community-server:6.0.12-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017"
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-student-service-db.rule=Host(`teachme-student-service.db.localhost`)"
      - "traefik.http.services.teachme-student-service-db.loadbalancer.server.port=8080"

  redis-cache:
    image: redis/redis-stack-server:latest
    ports:
      - "6379"
    networks:
      - teachme-network

  azurite-blob-storage:
    container_name: blob-storage
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    expose:
      - 10000
      - 10001
      - 10002
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob-storage-volume:/data mcr.microsoft.com/azure-storage/azurite
    networks:
      - teachme-network


volumes:
  blob-storage-volume:

secrets:
  maven_settings:
    file: ~/.m2/settings.xml

networks:
  teachme-network:
    external: true
  proxy-network:
    external: true