name: teachme-frontend

services:
  teachme-frontend:
    build:
      context: ./services/teachme-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/teachme-frontend:/app
      - /app/node_modules
    container_name: frontend
    environment:
      - VITE_WS_URI=ws://localhost:7777
    ports:
      - "5173:5173"
    networks:
      - teachme-network

networks:
  teachme-network:
    external: true