services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - teachme-network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - teachme-network

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik/traefik.yml:/traefik.yml:ro"
    networks:
      - proxy-network

  api-gateway:
    build:
      context: ./services/teachme-api-gateway
      dockerfile: Dockerfile
      secrets:
        - source: maven_settings
    container_name: api-gateway
    environment:
      - AUTH_SERVICE_URI=http://auth-service:8080
      - STUDENT_SERVICE_URI=http://student-service:8080
      - FRONTEND_URI=http://frontend:5173
      - COURSE_SERVICE_URI=http://course-service:8081
      - RATING_SERVICE_URI=http://rating-service:8080
      - CERTIFICATION_SERVICE_URI=http://certification-service:8080
      - FORUM_SERVICE_URI=http://forum-service:8080
      - SECURITY_JWT_SECRET_KEY
    ports:
      - "8888:8080"
      - "35729"
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-api-gateway.rule=Host(`teachme-api-gateway.localhost`)"
      - "traefik.http.services.teachme-api-gateway.loadbalancer.server.port=8080"
