name: teachme-course-service

services:
  course-service:
    build:
      context: ./services/teachme-course-service/courseservice
      dockerfile: Dockerfile
      secrets:
        - source: maven_settings
    container_name: course-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://user:pass@course-service-mongo-db:27017
      - SPRING_DATA_MONGODB_DATABASE=course
      - YOUTUBE_API_KEY
      - BASE_URL=http://auth-service:8080/api/v1/users/
      - FORUM_CREATED_URL=http://forum-service:8080/api/v1/forums
      - FORUM_DELETE_URL=http://forum-service:8080/api/v1/forums/
    ports:
      - "8080"
      - "8081"
      - "35729"
    depends_on:
      - mongo-db
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-course-service.rule=Host(`teachme-course-service.localhost`)"
      - "traefik.http.services.teachme-course-service.loadbalancer.server.port=8080"

  mongo-db:
    image: mongodb/mongodb-community-server:6.0.12-ubi8
    container_name: course-service-mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27019:27017"
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-course-service-db.rule=Host(`teachme-course-service.db.localhost`)"
      - "traefik.http.services.teachme-course-service-db.loadbalancer.server.port=8080"

secrets:
  maven_settings:
    file: ~/.m2/settings.xml

networks:
  teachme-network:
    external: true
  proxy-network:
    external: true
