name: teachme-notification-service

services:
  notification-service:
    build:
      context: ./services/teachme-notification-service
      dockerfile: Dockerfile.dev
      secrets:
        - source: maven_settings
    container_name: notification-service
    volumes:
      - ./services/teachme-notification-service:/app
      - ./services/teachme-notification-service/target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SECURITY_JWT_SECRET_KEY
      - SPRING_DATA_MONGODB_URI=mongodb://user:pass@notification-service-mongo-db:27017
      - SPRING_DATA_MONGODB_DATABASE=notifications
      - TEACHME_STUDENT_SERVICE_URL=http://student-service:8080
      - TEACHME_EMAIL_AZURE_FUNCTION_URL=http://mail-az-function
    ports:
      - "7777:8080"
      - "35729"
    depends_on:
      - mongo-db
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-notification-service.rule=Host(`teachme-notification-service.localhost`)"
      - "traefik.http.services.teachme-notification-service.loadbalancer.server.port=8080"

  mongo-db:
    image: mongodb/mongodb-community-server:6.0.12-ubi8
    container_name: notification-service-mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27025:27017"
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachme-notification-service-db.rule=Host(`teachme-notification-service.db.localhost`)"
      - "traefik.http.services.teachme-notification-service-db.loadbalancer.server.port=8080"

secrets:
  maven_settings:
    file: ~/.m2/settings.xml

networks:
  teachme-network:
    external: true
  proxy-network:
    external: true
