name: forum-service

services:
  forum-service:
    build:
      context: ./services/teachme-forum-service/forum
      dockerfile: DockerFile
      secrets:
        - source: maven_settings
    container_name: forum-service
    volumes:
      - ./services/forum-service:/app
      - ./services/forum-service/target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    ports:
      - "8080"
      - "35729"
    depends_on:
      - mongo-db
      - redis-cache
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forum-service.rule=Host(`forum-service.localhost`)"
      - "traefik.http.services.forum-service.loadbalancer.server.port=8080"

  mongo-db:
    image: mongodb/mongodb-community-server:6.0.12-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017"
    networks:
      - teachme-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forum-service-db.rule=Host(`forum-service.db.localhost`)"
      - "traefik.http.services.forum-service-db.loadbalancer.server.port=8080"

  redis-cache:
    image: redis/redis-stack-server:latest
    ports:
      - "6379"
    networks:
      - teachme-network

secrets:
  maven_settings:
    file: ~/.m2/settings.xml

networks:
  teachme-network:
    external: true
  proxy-network:
    external: true